title: Welcome!
author: Maya Vitrano
email: mayavitrano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My new site will showcase my coding abilities and passion for SE!

# social links
twitter_handle: # DO NOT include the @ character, or else the build will fail!
github_username:  mayavit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
